Use kIOMasterPortDefault if compiled with SDK<12
Compiling against Apple SDK older than 12.0 ends with errors:

error: use of undeclared identifier 'kIOMainPortDefault'

That is because `kIOMainPortDefault` was introduced in SDK 12.0
(Monterey) and before that the `kIOMasterPortDefault` should be used.

`kIOMasterPortDefault` was deprecated and was removed in SDK 12.0

References:
- https://developer.apple.com/documentation/iokit/kiomainportdefault
- https://developer.apple.com/documentation/iokit/kiomasterportdefault